version: "3.8"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: cookbook-image
    ports:
      - "3002:3002"
    volumes:
      - .:/home/node/
    environment:
      - PORT=3002
    command: "npm start"
